### PR TITLE
adding __init__ in the scripts dir since python3.7 requires that for …

### PR DESCRIPTION
**Pull request by jieltan**
…directories to be recognized as modules. it wasn't enforced in 3.6, but since 3.7 it is

### CODE REVIEW

**Comment by taoliug** [comment]
Please sign CLA so that I can merge your PR

**Comment by jieltan** [comment]
> Please sign CLA so that I can merge your PR

pretty sure I already did, I don't know why it hasn't updated

**Comment by taoliug** [comment]
Can you reply "@googlebot I signed it!" here?

**Comment by jieltan** [comment]
> Please sign CLA so that I can merge your PR

**Pull request merged**
