### PR TITLE
Fix typos/grammar in README & code comments

### PR DESCRIPTION
**Pull request by scottj97**
I believe my company rep signed the Google CLA this morning.

### CODE REVIEW

**Comment by taoliug** [comment]
Thanks for the fix!

**Comment by taoliug** [comment]
Hi Scott, I guess you are using your personal account which requires signing CLA. Can you please sign the CLA?

**Comment by scottj97** [comment]
The commits were all done using my arilinc.com email address, and these changes were made on behalf of my employer. From what I've read about the CLA, I should use the company-wide one. Perhaps our company CLA is not approved by Google yet?

**Comment by taoliug** [comment]
Ah, I thought you were one of my colleague at Google (exactly the same name :)), that's why I am wondering you need to sign CLA for this.
I cannot find arilinc in the list of corporate signers. Can you check with your employer if the CLA is approved? I may have to revert this PR because of this CLA issue. Sorry for the inconvenience. I am looking for to your future contribution.

**Pull request merged**
