### PR TITLE
Sphinx: Add generating pdf file

### PR DESCRIPTION
**Pull request by danghai**
I make PR to generate pdf file
relate #425

### CODE REVIEW

**Comment by taoliug** [comment]
Thanks, the formatting of PDF looks a bit weird though, do you know which file control the format ? I'd like to do some experiment.

**Comment by danghai** [comment]
I think *.rst file. To generate:
`sphinx-build -b pdf source . `

**Comment by danghai** [comment]
Do you enable the `travis`? Yesterday, I saw 3-4 die link in document (It happens in README too), CI will catch them.

**Comment by taoliug** [comment]
Will look into Travis enable in the next couple of days. Approve this PR first, I will check how to make the PDF doc looks better.

**Pull request merged**
