### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by adimay162**
Added bit manipulation support

### CODE REVIEW

**Comment by adimay162** [comment]
@googlebot I signed it!

**Comment by taoliug** [comment]
Looks like you still need to sign CLA, can you double check?

**Comment by taoliug** [comment]
Please let me know how would you want to proceed with this PR. I could help to create a PR to integrate these changes if you are OK.

**Comment by adimay162** [comment]
Hi,

We have an issue with the CLA.
Our company Mellanox is already signed on the CLA and my email is set on this group, but still it is claiming that I  have no CLA signed from my side.
Can you please advise?

Thanks
Adi

**Comment by taoliug** [comment]
Closing this PR as there's another PR opened for this.

**Pull request closed without merging**
