### PR TITLE
Add bit manipulation

### PR DESCRIPTION
**Pull request by adimay162**

### CODE REVIEW

**Comment by udinator** [comment]
Hi @adimay162, it looks like you haven't signed the CLA yet or there is some mismatch on the github email address that you are using, could you resolve this?

**Comment by adimay162** [comment]
Hi,

I am part of the Mellanox group that is signed on this CLA.

But for some reason it is not shown.

[cid:image002.jpg@01D5F176.202B6F10]
Can you please advise?
Thanks
Adi

**Comment by udinator** [comment]
@adimay162, can you run through the bulletpoints shown under the `Corporate signers` section and check if any of those is the case?

**Comment by taoliug** [comment]
@adimay162, thanks for your contribution. I will ask @weicaiyang to help with integrating this PR, and add Mellanox in the license header.

**Comment by taoliug** [comment]
@adimay162 , we have integrated your changes to the upstream (#518). Please review if everything looks good to you. The next step is to enable bit manipulation instructions generation.  I will file separate bug to track it.

**Comment by taoliug** [comment]
I am closing this PR as the code has been submitted

**Pull request closed without merging**
