### PR TITLE
Refactor the simulation flow

### PR DESCRIPTION
**Pull request by taoliug**
Refactor the comparison scripts to be easily integrated to the new run flow.

### CODE REVIEW

**Comment by scottj97** [comment]
Has the README been updated for this new flow? Is the `run` script now obsolete?

**Comment by taoliug** [comment]
Not yet, there are still some work to be done before switching to new flow.

**Comment by scottj97** [comment]
I noticed the SIM_SEED changes I made in `run` are not in the new flow.

**Comment by taoliug** [comment]
Just added here:
https://github.com/google/riscv-dv/commit/e108691b8c61912068d9bdfbe52818f0eb66ad79#diff-d831ee482f0df083d0b5076369af4b43

**Pull request merged**
