### PR TITLE
[Pygen] Add support for multi_harts

### PR DESCRIPTION
**Pull request by aneels3**
This PR adds the support for multi_hart configuration along with fixing the issue related to rcs of riscv_gen_config class.

### CODE REVIEW

**Comment by ishita71** [comment]
@googlebot I consent.

**Comment by aneels3** [comment]
Hi @udinator and @hodjat91, 
Can you please review the PR for me?
I am planning to create another PR.

**Review by udinator — APPROVED** [review]
LGTM in general, thanks!

**Comment by aneels3** [comment]
Hi @udinator 
I have rebased it.

**Pull request merged**
