### PR TITLE
[Pygen] Add coverage support for RV32M 

### PR DESCRIPTION
**Pull request by aneels3**

### CODE REVIEW

**Comment by ishita71** [comment]
@googlebot I consent

**Review by udinator — APPROVED** [review]
LGTM overall!
Could you please check that the coverage matches that of the SV RISCV-DV when using M extension?

**Comment by aneels3** [comment]
Hi @udinator 
Sorry for the late response on it.
I have compared the results with SV coverage and pyflow separately for the same assembly file generated using pyflow.
It seems like there is some discrepancy (difference of 5-10 %) in the percentage score for the instructions.
This is observed in the RV32I extension instructions as well.

I am working on the debugging of this issue.

**Comment by udinator** [comment]
@aneels3 - that's interesting...let's merge this PR but keep debugging the coverage mismatches.

**Pull request merged**
