### PR TITLE
Upgrade bitmanip v.0.92 to v.0.93, enable simultaneous use with v.1.00

### PR DESCRIPTION
**Pull request by vogelpi**
The main changes implemented by this PR are:
1. Support for bitmanip draft v.0.92 is dropped.
2. Remaining bitmanip instructions not ratified as part of v.1.00 of  the bitmanip spec are upgraded to the latest draft (v.0.93).
3. Simultaneous use of the v.1.00 bitmanip instructions and those instructions only part of draft v.0.93 is enabled.
4. Rename bext/bdep to bcompress/bdecompress. This is part of v.0.94. But it's needed as in v.0.93 as well as in v.1.00 sbext from Zbs is renamed to bext, leading to two completely different instructions having the same name.
5. Increase the MAX_INSTR_STR_LEN parameter to accomodate longer instruction names bdecompressw has 12 characters).

### CODE REVIEW

**Comment by vogelpi** [comment]
@weicaiyang it would be great if you could have a look at this.

**Review by weicaiyang — APPROVED** [review]
LGTM, thanks

**Comment by weicaiyang** [comment]
CI passed, but it got this error after merging this PR. Does anyone know what happens?

> Run ./scripts/metrics-regress.py $METRICS_REGRESSION_NAME $METRICS_PROJECT_ID
> Error, regression was not started. Response: 400:Bad Request {'message': 'Failed to get new access token using refresh token.', 'code': 'ERROR_REFRESHING_TOKEN'}
> Exit with code 1
> Error: Process completed with exit code 1.

**Comment by vogelpi** [comment]
Thanks a lot @weicaiyang ! Regarding the error, I have don't really have an idea what this is about. But it seems also previous PRs got the same error. Could it be that this metrics script got somehow outdated?

**Comment by weicaiyang** [comment]
> Thanks a lot @weicaiyang ! Regarding the error, I have don't really have an idea what this is about. But it seems also previous PRs got the same error. Could it be that this metrics script got somehow outdated?

I see. Let me file an issue for it.

**Pull request merged**
