### PR TITLE
Csr refactor

### PR DESCRIPTION
**Pull request by GregAC**
@ctopal @marnovandermaas @vogelpi PTAL

### CODE REVIEW

**Comment by MikeOpenHWGroup** [comment]
FWIW I applaud the goals of this PR.  Probably would have saved OpenHW some effort writing manual test-programs.

**Review by marnovandermaas — APPROVED** [review]
LGTM, thanks.

**Review by ctopal — APPROVED** [review]
LGTM, tested it within Ibex repository. Works as expected, thanks! 

Minor nit: The knob for generating writes to read-only CSRs maybe could be named `gen_csr_ro_writes`? I suggest it because an invalid write can happen because of some other reason as well.

**Comment by GregAC** [comment]
> The knob for generating writes to read-only CSRs maybe could be named gen_csr_ro_writes? I suggest it because an invalid write can happen because of some other reason as well.

Good suggestion I've made the change.
@weicaiyang please take a look

**Review by weicaiyang — APPROVED** [review]

**Pull request merged**
